### ISSUE TITLE
Doesn't appear to be playing well with StationPartsExpansionRedux

### ISSUE THREAD

**Issue by quade-ksp** [TedThompson/T.R.A.I.L.S.#1]
See this thread.

https://github.com/ChrisAdderley/StationPartsExpansionRedux/issues/213

**Comment by TedThompson** [comment]
I saw it, don't know what to make of it. 

Please zip up and send me your trails and station parts redux folders so I can see if I can reproduce it. 

Meanwhile, what does the screenshot with "hmmmm" above it mean?  Also, HOW did you determine trails was at fault?

⁣Get BlueMail for Android ​

**Comment by quade-ksp** [comment]
Won't attach as they appear to violate the 10MB limit of this Git.

Here are the URLs.

https://github.com/TedThompson/T.R.A.I.L.S./releases/download/1.8.1.6/TRAILSplus6.zip

https://github.com/ChrisAdderley/StationPartsExpansionRedux/releases/download/1.3.1/StationPartsExpansionRedux_1_3_1.zip

**Comment by quade-ksp** [comment]
I determined doing a "standard" binary sort of removing half the mods, reopening the game to see if the effect persisted, removing the other half, finding out which half of the mods maybe was the culprit and repeating until finding the actual mod.  This also tracks with something Chris Adderly said previously about Trails throwing an error in the logs.

**Comment by ChrisAdderley** [comment]
To help out:

```
[LOG 09:10:27.708] Load(Model): TRAILSplus/Parts/Agena/DockingPortAgena
[EXC 09:10:27.710] EndOfStreamException: Unable to read beyond the end of the stream.
	System.IO.BinaryReader.FillBuffer (System.Int32 numBytes) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.IO.BinaryReader.ReadInt32 () (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	PartReader.Read (UrlDir+UrlFile file) (at <394a98b9c7624adc895c04290da62640>:0)
	DatabaseLoaderModel_MU+<Load>d__1.MoveNext () (at <394a98b9c7624adc895c04290da62640>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <7d9ec060e791409ab3eb85c61e312ed6>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	<LoadObjects>d__89:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```
The error @quade-ksp reports is this one. It appears to make the next model in the loading list fail to load. Haven't seen that behaviour before, but that message is similar to one that appears when a corrupted animation is present on the part.

**Comment by TedThompson** [comment]
Any data may be helpful, so thanks for sending it. 

I still haven't had a look, holidays and all.

It does seem odd to me tho, since no ones else has this problem with trails alone, I'm having trouble imagining a scenario where the model file is corrupt. 

⁣Get BlueMail for Android ​

**Comment by ChrisAdderley** [comment]
Yes, I suspect it's actually neither of our mods and some esoteric mod interaction.
